version: "3"

services:
  2chat:
    build: .
    container_name: 2chat
    restart: unless-stopped
    ports:
      - "4200:4200"
    environment:
      - VIRTUAL_HOST=2chat.li
      - VIRTUAL_PORT=4200
      - LETSENCRYPT_HOST=2chat.li
    volumes:
      -  .:/app
    command: npm run start
    networks:
      - proxy
networks:
  proxy:
    external: True
