version: "3"

services:
  2chat:
    build: .
    container_name: 2chat
    restart: unless-stopped
    expose:
      - 4200
    environment:
      - VIRTUAL_HOST=2chat.li
      - VIRTUAL_PORT=4200
      - LETSENCRYPT_HOST=2chat.li
    volumes:
      -  .:/app
    command: npm run start
    networks:
      - proxy
  chat-api:
    build:
      context: ./ChatApi
      dockerfile: Dockerfile
    container_name: chat-api
    restart: unless-stopped
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=api.2chat.li
      - VIRTUAL_PORT=3000
      - NODE_ENV=production
    volumes:
      - ./ChatApi:/app
    command: npm run start
    networks:
      - proxy
networks:
  proxy:
    external: True
